version: "3"

services:

  mongo-fiber:
    image: mongo:4.4
    container_name: mongo-fiber
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=pass
      - MONGO_INITDB_DATABASE=fiber-hrms
      - TZ=Europe/Madrid
    ports:
     - "27027:27017"